# Generated by Django 3.1.6 on 2021-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='checksum_md5',
            field=models.CharField(max_length=32),
        ),
    ]
