# Generated by Django 3.1.6 on 2021-03-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image_file_thumb',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_list', to='api.group'),
        ),
    ]
