# Generated by Django 3.1.6 on 2021-04-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210325_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='image_file_thumb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
