# Generated by Django 3.1.6 on 2021-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mappoint_image_file_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='category_list',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget_category_list',
            field=models.ManyToManyField(related_name='budget_item_list', to='api.BudgetCategory'),
        ),
    ]
