# Generated by Django 3.1.6 on 2021-05-04 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210415_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_category_list', to='api.group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='map_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_list', to='api.mappoint'),
        ),
        migrations.AlterField(
            model_name='usermappoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_map_point_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
